#! /bin/bash

. ./utils
rapport_head
unset GREP_OPTIONS

if [ "x$1" != "x" ]; then
    to_test="$@"
else
    to_test='*.test'
fi

for i in $to_test; do
    echo -n "[         ] [ .. ] $i"
    ./$i \
        || exit_status=$?
done

rapport_tail

echo Here a summary of the failed tests:

sep 80 =
echo
grep -E '^\*\* FAIL' sum.org | sed -e 's#^\*\* FAIL =\(.*\)=#\1#' | nl
sep 80 =
echo

nb=`grep -E '^\*\* ' sum.org | wc -l`
pass=`grep -E '^\*\* PASS' sum.org | wc -l`
fail=`grep -E '^\*\* FAIL' sum.org | wc -l`

echo "`wc -l < sum.dat | sed -e "#^ *##"` $nb $pass $fail 0" >> sum.dat

echo $pass/$nb tests pass.

if [ "x$fail" != "x0" ]; then
    echo `tput setaf 1`$fail`tput init` tests have failed.
fi

gnuplot all.plot
gnuplot fail.plot

emacs=emacs23
if which $emacs > /dev/null; then
    echo Make html report
    $emacs --batch --visit "sum.org" --funcall org-export-as-html > /dev/null 2>&1
    echo Make pdf report
    $emacs --batch --visit "sum.org" --funcall org-export-as-pdf > /dev/null 2>&1
else
    echo Emacs not present on the system, will not generate html/pdf report.
fi

if [ "x$fail" != "x0" ]; then
    exit 1
else
    exit 0
fi
