#! /bin/bash

. ./utils
rapport_head

to_test='*.test'
res() {
    echo -e "\r[`tput setaf $1`$2`tput init`"
}
full_res() {
    echo -e "\r[`tput setaf $1`$2`tput init`] $3"
}
nb=0
pass=0
fail=0
skip=
for i in $to_test; do
    nb=$(($nb + 1))
    echo -n "[ .. ] $i"
    exit_status=$(./$i) #> $i.log 2>&1
    if [ "x$exit_status" != "x0" ]; then
        if [ "x$exit_status" = "x77" ]; then
            res 3 skip
            skip=$(($skip + 1))
        else
            fail=$(($fail + 1))

            if [ "x$exit_status" = "x99" ]; then
                full_res 1 "epic fail" "$i"
            else
                res 1 fail
            fi
        fi
    else
        pass=$(($pass + 1))
        res 2 " ok"
    fi
done

rapport_tail

echo Make html report
emacs23 --batch --visit "sum.org" --funcall org-export-as-html > /dev/null 2>&1
echo Make pdf report
emacs23 --batch --visit "sum.org" --funcall org-export-as-pdf > /dev/null 2>&1

echo $pass/$nb tests pass.

if [ "x$fail" != "x0" ]; then
    echo $fail tests has failed.
    exit 1
fi


exit 0
