#! /bin/sh

set -e

out_report=sum.org
out_tmp=sum.org.tmp
out_report_fail=sum.org.fail
out_report_pass=sum.org.pass

me=$0

stderr () {
  local i
  for i
  do
    echo "$i"
  done | sed -e "s,^,$me: ," >&2
}

rapport_head() {
    # Initialize the output file
    cat >"$out_report"<<.
#+OPTIONS: toc:2
#+TODO: FAIL EPIC-FAIL | PASS SKIP
.
    cat >$out_report_pass<<.
* Passed Tests
.
    cat >$out_report_fail<<.
* Failed Test
.
    rm -f $out_report_tmp
}
rapport_tail() {
    cat $out_report_fail >>$out_report
    cat $out_report_pass >>$out_report
    rm -f $out_report_fail $out_report_pass $out_report_tmp out.exp out.eff err.eff
}

#######
# run #
#######
run() {
    test_number=$(($test_number + 1))
    local sta_exp=$1
    shift
    local out_report_exp=$1
    shift
    case $out_report_exp in
        ('') : >out.exp;;
        (-) cat >out.exp;;
        (out.exp|stdout);;
        (*)
            cat >out.exp <<.
$out_report_exp
.
            ;;
    esac
    local name="$1"
    shift
    local cmd="$1"
    shift
    local sta_eff=0
    fail=false
    # Run and check the output code
    ($cmd "$@")>out.eff 2>err.eff          \
        || staf_eff=$?

    # Check the diff
    if [ ! $sta_eff -eq $sta_exp ]; then
        fail=true
    fi

    if ! cmp -s out.eff out.exp; then
        fail=true
    fi

    ####################
    # Write the report #
    ####################
    if $fail; then
        {
            ###############
            # Fail Status #
            ###############
            cat <<.
** FAIL =$name=
#+BEGIN_SRC sh
  $cmd $@
#+END_SRC
.
            # Exit Code
            if [ ! $sta_eff -eq $sta_exp ]; then
                cat <<.
*** Exit Codes
    - Expected :: $sta_exp
    - Effective :: $sta_eff
.
            else
                cat <<.
*** Exit Code
    - Expected :: $sta_exp
.
            fi

            # Outputs
            # Display the expected standard output
            cat <<.
*** Expected Standard Output
#+BEGIN_EXAMPLE
$(if test "x$(stat -c%s "out.exp")" = "x0"; then
      echo No output
  else
      cat out.exp
  fi
)
#+END_EXAMPLE
.
            # If an error appends display the effective one and the
            # error output.
            if ! cmp -s out.eff out.exp; then
                cat <<.
*** Effective Standard Output
#+BEGIN_EXAMPLE
$(if test "x$(stat -c%s "out.eff")" = "x0"; then
      echo No output
  else
      cat out.eff
  fi
)
#+END_EXAMPLE
*** Diff Between Effective and Expected Outputs
#+BEGIN_EXAMPLE
$(diff out.eff out.exp && echo No diff)
#+END_EXAMPLE

*** Effective Error Output
#+BEGIN_EXAMPLE
$(if test "x$(stat -c%s "err.eff")" = "x0"; then
      echo No output
  else
      cat err.eff
  fi
)
#+END_EXAMPLE
.
            fi
        }>>$out_report_fail
    else
        {
            ##################
            # Success Status #
            ##################
            cat <<.
** PASS =$name=
#+BEGIN_SRC sh
     $cmd $@
#+END_SRC
*** Exit Code
    - Expected :: $sta_exp
*** Standard Output
#+BEGIN_EXAMPLE
$(if test "x$(stat -c%s "out.exp")" = "x0"; then
      echo No Output
  else
      cat out.exp
  fi
)
#+END_EXAMPLE
*** Error Output
$(if test "x$(stat -c%s "err.eff")" = "x0"; then
      echo No Output
  else
      cat out.exp
  fi
)

.
        }>>$out_report_pass
    fi
}
